import Coins from "@/components/icons/coins";
import { IconProps } from "@/components/icons/type";
import {
  AF,
  AM,
  AU,
  AZ,
  BH,
  CAN,
  CH,
  CN,
  DK,
  EU,
  GE,
  HK,
  IN,
  IQ,
  JPN,
  KW,
  MY,
  NO,
  NZ,
  OM,
  PK,
  QA,
  RU,
  SA,
  SE,
  SG,
  SY,
  TH,
  TR,
  UAE,
  UK,
  US,
} from "@/components/icons/flags";
import Gold from "@/components/icons/gold";
import TetherIcon from "@/components/icons/usdt";

export const ASSETS_MAP: Record<string, { name: string; name_fa: string }> = {
  // Gold and related assets
  IR_COIN_EMAMI: { name: "Emami Coin", name_fa: "سکه امامی" },
  IR_COIN_BAHAR: { name: "Azadi Coin", name_fa: "سکه بهار آزادی" },
  IR_COIN_HALF: { name: "Half Azadi Coin", name_fa: "نیم سکه" },
  IR_COIN_QUARTER: { name: "Quarter Azadi Coin", name_fa: "ربع سکه" },
  IR_COIN_1G: { name: "Gerami Coin", name_fa: "سکه یک گرمی" },
  IR_GOLD_18K: { name: "18 Karat Gold", name_fa: "طلای 18 عیار" },
  IR_GOLD_24K: { name: "24 Karat Gold", name_fa: "طلای 24 عیار" },
  IR_GOLD_MELTED: { name: "Melted Gold", name_fa: "طلای آب‌شده نقدی" },
  XAUUSD: { name: "Gold Ounce (USD $)", name_fa: "انس طلا" },

  // Currency
  USD: { name: "United States Dollar", name_fa: "دلار" },
  EUR: { name: "Euro", name_fa: "یورو" },
  AED: { name: "United Arab Emirates Dirham", name_fa: "درهم امارات" },
  GBP: { name: "British Pound", name_fa: "پوند" },
  TRY: { name: "Turkish Lira", name_fa: "لیر ترکیه" },
  CNY: { name: "Chinese Yuan", name_fa: "یوآن چین" },
  JPY: { name: "100 Japanese Yen", name_fa: "یکصد ین ژاپن" },
  CAD: { name: "Canadian Dollar", name_fa: "دلار کانادا" },
  AUD: { name: "Australian Dollar", name_fa: "دلار استرالیا" },
  CHF: { name: "Swiss Franc", name_fa: "فرانک سوئیس" },
  AFN: { name: "Afghan Afghani", name_fa: "افغانی" },
  IQD: { name: "Iraqi Dinar", name_fa: "دینار عراق" },
  RUB: { name: "Russian Ruble", name_fa: "روبل روسیه" },
  THB: { name: "Thai Baht", name_fa: "بات تایلند" },
  AMD: { name: "Armenian Dram", name_fa: "درام ارمنستان" },
  INR: { name: "Indian Rupee", name_fa: "روپیه هند" },
  SEK: { name: "Swedish Krona", name_fa: "کرون سوئد" },
  DKK: { name: "Danish Krone", name_fa: "کرون دانمارک" },
  MYR: { name: "Malaysian Ringgit", name_fa: "رینگیت مالزی" },
  KWD: { name: "Kuwaiti Dinar", name_fa: "دینار کویت" },
  SYP: { name: "Syrian Pound", name_fa: "لیر سوریه" },
  OMR: { name: "Omani Rial", name_fa: "ریال عمان" },
  SGD: { name: "Singapore Dollar", name_fa: "دلار سنگاپور" },
  AZN: { name: "Azerbaijani Manat", name_fa: "منات آذربایجان" },
  NZD: { name: "New Zealand Dollar", name_fa: "دلار نیوزیلند" },
  HKD: { name: "Hong Kong Dollar", name_fa: "دلار هنگ کنگ" },
  SAR: { name: "Saudi Riyal", name_fa: "ریال عربستان" },
  PKR: { name: "Pakistani Rupee", name_fa: "روپیه پاکستان" },
  BHD: { name: "Bahraini Dinar", name_fa: "دینار بحرین" },
  QAR: { name: "Qatari Riyal", name_fa: "ریال قطر" },
  NOK: { name: "Norwegian Krone", name_fa: "کرون نروژ" },
  GEL: { name: "Georgian Lari", name_fa: "لاری گرجستان" },

  // Cryptocurrency
  BTC: { name: "Bitcoin", name_fa: "بیت کوین" },
  ETH: { name: "Ethereum", name_fa: "اتریوم" },
  USDT_IRT: { name: "Tether", name_fa: "تتر" },
};

export const ICONS_MAP: Record<string, (props: IconProps) => JSX.Element> = {
  USD: US,
  EUR: EU,
  GBP: UK,
  CHF: CH,
  AUD: AU,
  RUB: RU,
  TRY: TR,
  AFN: AF,
  AED: UAE,
  CNY: CN,
  JPY: JPN,
  CAD: CAN,
  IQD: IQ,
  THB: TH,
  AMD: AM,
  INR: IN,
  SEK: SE,
  DKK: DK,
  MYR: MY,
  KWD: KW,
  SYP: SY,
  OMR: OM,
  SGD: SG,
  AZN: AZ,
  NZD: NZ,
  HKD: HK,
  SAR: SA,
  PKR: PK,
  BHD: BH,
  QAR: QA,
  NOK: NO,
  GEL: GE,
  IR_COIN_EMAMI: Coins,
  IR_COIN_BAHAR: Coins,
  IR_COIN_HALF: Coins,
  IR_COIN_QUARTER: Coins,
  IR_COIN_1G: Coins,
  XAUUSD: Gold,
  IR_GOLD_MELTED: Gold,
  IR_GOLD_18K: Gold,
  IR_GOLD_24K: Gold,
  USDT_IRT: TetherIcon,
};
