import Coins from "@/components/icons/coins";
import { IconProps } from "@/components/icons/type";
import {
  AF,
  AM,
  AU,
  AZ,
  BH,
  CAN,
  CH,
  CN,
  DK,
  EU,
  GE,
  HK,
  IN,
  IQ,
  JPN,
  KW,
  MY,
  NO,
  NZ,
  OM,
  PK,
  QA,
  RU,
  SA,
  SE,
  SG,
  SY,
  TH,
  TR,
  UAE,
  UK,
  US,
} from "@/components/icons/flags";
import Gold from "@/components/icons/gold";

export const ASSETS_MAP: Record<string, { code: string; name: string }> = {
  // Gold and related assets
  "سکه امامی": { code: "emami", name: "Emami Coin" },
  "سکه بهار آزادی": { code: "azadi", name: "Azadi Coin" },
  "نیم سکه": { code: "azadi_half", name: "Half Azadi Coin" },
  "ربع سکه": { code: "azadi_quarter", name: "Quarter Azadi Coin" },
  "سکه گرمی": { code: "gerami", name: "Gerami Coin" },
  "گرم طلای 18 عیار": { code: "gold18", name: "18 Karat Gold" },
  "گرم طلای 24 عیار": { code: "gold24", name: "24 Karat Gold" },
  "مثقال طلا": { code: "mesghal", name: "Gold Mesghal" },
  "انس جهانی طلا": { code: "ounce", name: "Gold Ounce (USD $)" },

  // Currency
  دلار: { code: "usd", name: "United States Dollar" },
  یورو: { code: "eur", name: "Euro" },
  "درهم امارات": { code: "aed", name: "United Arab Emirates Dirham" },
  پوند: { code: "gbp", name: "British Pound" },
  "لیر ترکیه": { code: "try", name: "Turkish Lira" },
  "یوان چین": { code: "cny", name: "Chinese Yuan" },
  "ین ژاپن": { code: "jpy", name: "Japanese Yen" },
  "دلار کانادا": { code: "cad", name: "Canadian Dollar" },
  "دلار استرالیا": { code: "aud", name: "Australian Dollar" },
  "فرانک سوئیس": { code: "chf", name: "Swiss Franc" },
  افغانی: { code: "afn", name: "Afghan Afghani" },
  "دینار عراق": { code: "iqd", name: "Iraqi Dinar" },
  "روبل روسیه": { code: "rub", name: "Russian Ruble" },
  "بات تایلند": { code: "thb", name: "Thai Baht" },
  "درام ارمنستان": { code: "amd", name: "Armenian Dram" },
  "روپیه هند": { code: "inr", name: "Indian Rupee" },
  "کرون سوئد": { code: "sek", name: "Swedish Krona" },
  "کرون دانمارک": { code: "dkk", name: "Danish Krone" },
  "صد ین ژاپن": { code: "jpy", name: "100 Japanese Yen" },
  "رینگیت مالزی": { code: "myr", name: "Malaysian Ringgit" },
  "دینار کویت": { code: "kwd", name: "Kuwaiti Dinar" },
  "لیر سوریه": { code: "syp", name: "Syrian Pound" },
  "ریال عمان": { code: "omr", name: "Omani Rial" },
  "دلار سنگاپور": { code: "sgd", name: "Singapore Dollar" },
  "منات آذربایجان": { code: "azn", name: "Azerbaijani Manat" },
  "دلار نیوزیلند": { code: "nzd", name: "New Zealand Dollar" },
  "دلار هنگ کنگ": { code: "hkd", name: "Hong Kong Dollar" },
  "ریال عربستان": { code: "sar", name: "Saudi Riyal" },
  "روپیه پاکستان": { code: "pkr", name: "Pakistani Rupee" },
  "دینار بحرین": { code: "bhd", name: "Bahraini Dinar" },
  "ریال قطر": { code: "qar", name: "Qatari Riyal" },
  "کرون نروژ": { code: "nok", name: "Norwegian Krone" },
  "لاری گرجستان": { code: "gel", name: "Georgian Lari" },

  // Cryptocurrency
  "بیت کوین": { code: "btc", name: "Bitcoin" },
  اتریوم: { code: "eth", name: "Ethereum" },
};

export const ICONS_MAP: Record<string, (props: IconProps) => JSX.Element> = {
  usd: US,
  eur: EU,
  gbp: UK,
  chf: CH,
  aud: AU,
  rub: RU,
  try: TR,
  afn: AF,
  aed: UAE,
  cny: CN,
  jpy: JPN,
  cad: CAN,
  iqd: IQ,
  thb: TH,
  amd: AM,
  inr: IN,
  sek: SE,
  dkk: DK,
  myr: MY,
  kwd: KW,
  syp: SY,
  omr: OM,
  sgd: SG,
  azn: AZ,
  nzd: NZ,
  hkd: HK,
  sar: SA,
  pkr: PK,
  bhd: BH,
  qar: QA,
  nok: NO,
  gel: GE,
  emami: Coins,
  azadi: Coins,
  azadi_half: Coins,
  azadi_quarter: Coins,
  gerami: Coins,
  ounce: Gold,
  mesghal: Gold,
  gold18: Gold,
  gold24: Gold,
};
