export const ASSETS_MAP: Record<string, { name: string }> = {
  aed: { name: "United Arab Emirates Dirham" },
  afn: { name: "Afghan Afghani" },
  amd: { name: "Armenian Dram" },
  aud: { name: "Australian Dollar" },
  azn: { name: "Azerbaijani Manat" },
  bhd: { name: "Bahraini Dinar" },
  cad: { name: "Canadian Dollar" },
  chf: { name: "Swiss Franc" },
  cny: { name: "Chinese Yuan" },
  dkk: { name: "Danish Krone" },
  eur: { name: "Euro" },
  gbp: { name: "British Pound" },
  hkd: { name: "Hong Kong Dollar" },
  inr: { name: "Indian Rupee" },
  iqd: { name: "Iraqi Dinar" },
  jpy: { name: "Japanese Yen" },
  kwd: { name: "Kuwaiti Dinar" },
  myr: { name: "Malaysian Ringgit" },
  nok: { name: "Norwegian Krone" },
  omr: { name: "Omani Rial" },
  qar: { name: "Qatari Riyal" },
  rub: { name: "Russian Ruble" },
  sar: { name: "Saudi Riyal" },
  sek: { name: "Swedish Krona" },
  sgd: { name: "Singapore Dollar" },
  thb: { name: "Thai Baht" },
  try: { name: "Turkish Lira" },
  usd: { name: "United States Dollar" },
  azadi: { name: "Azadi Coin" },
  azadi_half: { name: "Half Azadi Coin" },
  azadi_quarter: {
    name: "Quarter Azadi Coin",
  },
  gerami: { name: "Gerami Coin" },
  emami: { name: "Emami Coin" },
  gol18: { name: "18 Karat Gold" },
  mithqal: { name: "Mithqal Gold" },
  ounce: { name: "Gold Ounce" },
};
